### ISSUE TITLE
Cannot run specs when cursor is inside string interpolation

### ISSUE THREAD

**Issue by jacob-carlborg** [rspec/rspec.tmbundle#100]
When I have the cursor inside a string interpolation and press Cmd+R to run the specs I get an error. Here's an example of a spec that shows the problem:

```ruby
describe 'subject' do
  it 'does something' do
    expect(true).to be "#{tru|e}"
  end
end
```

In the above code, the pipe symbol (`|`) represents the position of the cursor. This is the error I get:

```
NoMethodError: undefined method ‘describe’ for main:Object

method <main>	in foo_spec.rb at line 1
```

If I place the cursor outside the curly braces, but still inside the string literal it works. I'm guessing there's some issue with the scope and that it's the regular Ruby runner that is executed instead of the RSpec runner. When I run Bundles -> Ruby -> Run I get the same error regardless of where the cursor is located.

**Comment by noniq** [comment]
Thanks, should be fixed now. Bundle should be updated automatically soon (cc @infininight).

**Comment by jacob-carlborg** [comment]
This issue also occurs for the "Run Single Example" command.

**Comment by noniq** [comment]
Thanks, fixed in ee5e22fd015bd463!

**Comment by infininight** [comment]
Deployed, you should see your bundle in TextMate update within a few hours.

**Comment by jacob-carlborg** [comment]
It works now. Awesome, thanks :smiley:
