### ISSUE TITLE
Problems running with binding.pry

### ISSUE THREAD

**Issue by jacob-carlborg** [rspec/rspec.tmbundle#102]
Previously if I had forgot `binding.pry` somewhere in the code the execution didn't halt and the tests continued to run. This is not the case anymore. A bit annoying when you forget to remove `binding.pry` and have to force quit the ruby instance running the command.

I'm suspecting it's the a81c3f9c7395d72616ddc82ce5963c113334f7b5 commit that caused this new behavior.

**Comment by noniq** [comment]
Hm, for me it seems to work as before: If I run specs containing `binding.pry`, I see a lot of garbage in  the output window, but the spec run finishes normally (see screenshot).

Which versions of Ruby, RSpec, Pry etc. are you using?

![bildschirmfoto 2015-10-15 um 15 17 22](https://cloud.githubusercontent.com/assets/244158/10514739/eb613704-734f-11e5-8c9e-4ffa164c44f0.png)

**Comment by jacob-carlborg** [comment]
```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
$ pry -v
Pry version 0.10.1 on Ruby 2.1.5
$ rspec -v
3.3.2
```

**Comment by gkellogg** [comment]
I find the same thing with byebug

ruby 2.1.5p273
byebug (6.0.2, 5.0.0)
rspec 3.3.2

**Comment by noniq** [comment]
Thanks, should be fixed now!

**Comment by jacob-carlborg** [comment]
Thanks.
