### ISSUE TITLE
rvm_wrapper error after Sierra upgrade

### ISSUE THREAD

**Issue by glennfu** [rspec/rspec.tmbundle#108]
I just recently ran the macOS Sierra upgrade to 10.12.6 and after that, my Spec integration in TM has broken. Here's the error I get when running specs:

```
Failure running “Run Single Example”.
/Users/Glenn/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/bin/rvm_wrapper (Errno::ENOENT)
	from /Users/Glenn/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /Users/Glenn/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:63:in `block in run_rspec'
	from /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:61:in `chdir'
	from /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:61:in `run_rspec'
	from /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:53:in `run'
	from /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:43:in `run_focussed'
	from /tmp/textmate-command-49949.rb:3:in `<main>'
```

The place I believe that path is being generated is here: https://github.com/textmate/ruby.tmbundle/blob/bd70e6aad45e0890cf257fa9a6663dbe1ffecdc1/Support/lib/executable.rb#L98 in the `Ruby.tmbundle`.

I've been digging around a bit but haven't managed to fix this yet. Anyone run into this, or have any idea what to do to fix it?

**Comment by noniq** [comment]
Thanks for the detailled report. I suspect that, at the place you mentioned, `ENV['TM_BUNDLE_SUPPORT']` is meant to point to the Ruby bundle’s support directory, but points to the RSpec bundle instead, because the RSpec bundle is declaring the Ruby bundle as a dependency (since 40ce3d9107647895c5db2920518b6cfa2ad07de6). I’m afraid I have to think a bit about how this can be fixed (of course I’m open for any suggestions :-)

**Comment by noniq** [comment]
I think I found a solution (see above). Does this work for you? (Note that the fix is in the Ruby bundle, not the RSpec bundle).

**Comment by glennfu** [comment]
This works for me, thanks!!

**Comment by noniq** [comment]
Great, so I’m going to close this issue here, hoping that the fix for the Ruby bundle will be merged soon :-)
