### ISSUE TITLE
Console HTML output is escaped

### ISSUE THREAD

**Issue by jmuheim** [rspec/rspec.tmbundle#110]
My console output looks like this:

![image](https://user-images.githubusercontent.com/1814983/33738486-ad57c158-db99-11e7-978d-adecef24c9bd.png)

What's wrong?

**Comment by noniq** [comment]
Could you provide a minimal app to reproduce this? I suspect some kind of race condition when capturing the output.

**Comment by jmuheim** [comment]
Just check out my app then run a spec, e.g.:

https://github.com/jmuheim/base/blob/master/spec/models/page_spec.rb

**Comment by noniq** [comment]
Sorry, can't reproduce: Output after running `page_spec.rb` looks like this for me:

<img width="1129" alt="bildschirmfoto 2017-12-16 um 22 52 50" src="https://user-images.githubusercontent.com/244158/34074641-f04dc6c6-e2b3-11e7-92dd-a203b5a5fdea.png">

Is there a way to reliably reproduce the behaviour you’ve encountered?

**Comment by noniq** [comment]
Closing because it seems stale. Feel free to reopen if you have any updates!

**Comment by jmuheim** [comment]
After reinstall macOS, it seems to be working on my side, too. Thank you!
