### ISSUE TITLE
Symbol list contains `context` + `it` + a combination of both on top with nested describe blocks

### ISSUE THREAD

**Issue by DivineDominion** [rspec/rspec.tmbundle#112]
## Without spacing

File:

```ruby
describe "outer subject" do
  describe "inner subject" do
    it "in describe" do
    end
    
    context "context" do
      it "in context" do 
      end
      
      it "in context 2" do
      end
    end
  end  
end
```

Symbol list is mangled:
![Screenshot 2019-03-28 at 10 50 19](https://user-images.githubusercontent.com/59080/55147833-6cb77100-5147-11e9-93c2-d8e0fe2a7dad.png)

## With spacing

File:

```ruby
describe "outer subject" do
  
  describe "inner subject" do
    
    it "in describe" do
    end

    context "context" do

      it "in context" do 
      end

      it "in context 2" do
      end
    end
  end  
end
```

Symbol list looks fine:

![Screenshot 2019-03-28 at 10 51 00](https://user-images.githubusercontent.com/59080/55147874-7f31aa80-5147-11e9-94ed-fa4e104a7bd9.png)

----

When I disable either the symbol list settings from the bundle for either behaviors or examples, the problem goes away.

I strongly suspect that the problem is two scopes touching. When I place the cursor at the beginning of a line with an `it` example, the current scope stays the same, but TextMate reports the _Left Scope_ (e.g. scope up to before the cursor) to be different: without empty lines, the _Left Scope_ is `meta.rspec.behavior`.

![Screenshot 2019-03-28 at 10 53 07](https://user-images.githubusercontent.com/59080/55148122-e94a4f80-5147-11e9-9b0f-e61c90dcd846.png) ![Screenshot 2019-03-28 at 10 53 17](https://user-images.githubusercontent.com/59080/55148123-e94a4f80-5147-11e9-9d5b-7b904c01c10f.png)

I'm not very proficient with  TextMate bundle building. Could the language grammar be changed to reflect this? Or can we adjust the Symbol List scope selectors to take this into account? (I tried by subtracting one from the other, but to no avail.)

**Comment by noniq** [comment]
Thanks for your detailed report! The issue was indeed because of the scopes touching, making the scope not include the newline at EOL seems to be a decent fix.

**Comment by DivineDominion** [comment]
Oh, that was an easy one, great :) Is there a way to make TextMate auto-updater pull changes from the repo? (My installed version is reported to be from Sep 2nd, 2017)

**Comment by noniq** [comment]
Changes get picked up automatically sooner or later, but let's see if pinging @infininight speeds things up :)
