### ISSUE TITLE
Add gutter marks for failures

### ISSUE THREAD

**Issue by noniq** [rspec/rspec.tmbundle#93]
Yesterday’s TextMate release (alpha.9575) added support for setting (and clearing) gutter marks via `mate`: https://github.com/textmate/textmate/blob/v2.0-alpha.9575/Applications/TextMate/about/Changes.md#2014-10-15-v20-alpha9575

This would make a great addition for the RSpec bundle – I think I'll give it a try soon; if anyone else wants to do a PR: Go for it! :smiley:

**Comment by noniq** [comment]
Implemented in bf8b559085ec5a.

**Comment by noniq** [comment]
Please update bundle index, @infininight :)

**Comment by infininight** [comment]
And deployed.
