### ISSUE TITLE
Backtrace broken with latest RSpec

### ISSUE THREAD

**Issue by jacob-carlborg** [rspec/rspec.tmbundle#98]
The backtrace is broken when using RSpec 3.3.1, possible older versions as well. The HTML for the links in the backtrace are escaped. See the discussion started here https://github.com/rspec/rspec-core/commit/74a286d1fe44fe6a3a6a248ee2e92718b7353e71#commitcomment-12159927.

Separate question. Based on myronmarston's [last reply](https://github.com/rspec/rspec-core/commit/74a286d1fe44fe6a3a6a248ee2e92718b7353e71#commitcomment-12163475), perhaps the bundle should be moved to the TextMate namespace/project?

CC @myronmarston @JonRowe @infininight @sorbits

**Comment by noniq** [comment]
Fixed with https://github.com/rspec/rspec.tmbundle/commit/d3644929e12edd01d2410ed6aa209735b8227398
